# pod-a.yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-a
  labels:
    app: pod-a
spec:
  serviceAccountName: pod-a-sa
  containers:
  - name: busybox
    image: busybox
    command:
      - sleep
      - "3600"

