# role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-a-to-pod-b-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: pod-a-sa
  namespace: default
roleRef:
  kind: Role
  name: pod-b-access-role
  apiGroup: rbac.authorization.k8s.io

