version: 0.2

env:
  parameter-store:
    DOCKER_USERNAME: /myapp/docker-credentials/username
    DOCKER_PASSWORD: /myapp/docker-credentials/password
    DOCKER_URL: /myapp/docker-registry/url
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - "pip install -r AWS_CodePipeline_CICD/simple-python-app/requirements.txt"
      - echo "Docker_Url:" "$DOCKER_URL"
      - echo "Docker Username:" "$DOCKER_USERNAME"

  build:
    commands:
      - echo "Building the image..."
      - cd "AWS_CodePipeline_CICD/simple-python-app"
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t "$DOCKER_USERNAME/simple-python-flask-app:latest" .
      - docker push "$DOCKER_USERNAME/simple-python-flask-app:latest"
  post_build:
    commands:
      - echo "Build is successful"
artifacts:
  files:
    - '**/*'
  base-directory: ../simple-python-app

